---
title:  |
        | Electoral Systems, Competition, and Incentives for Corruption
author: 
  - Umberto Mignozzetti[^umberto]
date: \today
thanks: "I thank Livio DiLonardo, Saad Gulzar, Cathy Hafer, Carlo Holz, Dimitri Landa, Adam Przeworski, Howard Rosenthal, Renard Sexton, Denis Stukal, and Scott Tyson for their comments. I also thank participants at APSA, MPSA, NYU PE Seminar, and SPSA. All materials required to replicate this study are available at <https://github.com/umbertomig/electoral-systems-corruption>."
abstract: "This is my abstract."
abstractspacing: double
keywords: Political Corruption; District Magnitude; Single-member districts; Multi-member districts; Welfare; Brazil
#jelcodes: HXXXX
fontsize: 11pt
margin: 2cm
urlcolor: darkblue
linkcolor: Mahogany
citecolor: Mahogany
spacing: double
papersize: a4paper
bibliography: references.bib
biblio-style: apalike
output:
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    number_sections: yes
    keep_tex: no
    toc: no
    toc_depth: 3
    template: article-template.latex
    md_extensions: +raw_attribute
---

```{r, message=FALSE, warning=FALSE, echo=FALSE, results='hide'}
# Knitr options
knitr::opts_chunk$set(fig.pos = "H") # holds figure position
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE, echo=FALSE, results='hide'}
# XXXX
```

[^umberto]: Visiting Assistant Professor, Quantitative Theory and Methods Department, Emory University, <umberto.mignozzetti@emory.edu>, <http://umbertomig.com>. Corresponding author.

\newpage

# Introduction
\label{sec:intro}

Here goes the intro.

# Theory
\label{sec:theory}

Here goes the theory.

# Background on the Brazilian Case
\label{sec:background}

Here goes the bozo.

# Results
\label{sec:results}

Here goes the results.

# Discussion
\label{sec:discussion}

Here goes the discussion.

\newpage
\setlength{\parindent}{0cm}
\setlength{\parskip}{5pt}